// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentPerformanceApi.Data;

#nullable disable

namespace StudentPerformanceApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260519144530_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("StudentPerformanceApi.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 10, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2217),
                            StudentId = 1,
                            SubjectId = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 18, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2235),
                            StudentId = 1,
                            SubjectId = 2,
                            Value = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 3, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2237),
                            StudentId = 1,
                            SubjectId = 3,
                            Value = 2
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 18, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2239),
                            StudentId = 1,
                            SubjectId = 4,
                            Value = 4
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 4, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2240),
                            StudentId = 1,
                            SubjectId = 5,
                            Value = 2
                        },
                        new
                        {
                            Id = 6,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 3, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2244),
                            StudentId = 2,
                            SubjectId = 1,
                            Value = 2
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 30, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2245),
                            StudentId = 2,
                            SubjectId = 2,
                            Value = 4
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 3, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2246),
                            StudentId = 2,
                            SubjectId = 3,
                            Value = 3
                        },
                        new
                        {
                            Id = 9,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 16, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2247),
                            StudentId = 2,
                            SubjectId = 4,
                            Value = 4
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 14, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2250),
                            StudentId = 2,
                            SubjectId = 5,
                            Value = 5
                        },
                        new
                        {
                            Id = 11,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 10, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2251),
                            StudentId = 3,
                            SubjectId = 1,
                            Value = 3
                        },
                        new
                        {
                            Id = 12,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 7, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2252),
                            StudentId = 3,
                            SubjectId = 2,
                            Value = 2
                        },
                        new
                        {
                            Id = 13,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 17, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2253),
                            StudentId = 3,
                            SubjectId = 3,
                            Value = 5
                        },
                        new
                        {
                            Id = 14,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 7, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2254),
                            StudentId = 3,
                            SubjectId = 4,
                            Value = 2
                        },
                        new
                        {
                            Id = 15,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 3, 26, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2255),
                            StudentId = 3,
                            SubjectId = 5,
                            Value = 2
                        },
                        new
                        {
                            Id = 16,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 18, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2265),
                            StudentId = 4,
                            SubjectId = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 17,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 16, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2266),
                            StudentId = 4,
                            SubjectId = 2,
                            Value = 2
                        },
                        new
                        {
                            Id = 18,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 14, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2269),
                            StudentId = 4,
                            SubjectId = 3,
                            Value = 3
                        },
                        new
                        {
                            Id = 19,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 18, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2270),
                            StudentId = 4,
                            SubjectId = 4,
                            Value = 5
                        },
                        new
                        {
                            Id = 20,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 1, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2271),
                            StudentId = 4,
                            SubjectId = 5,
                            Value = 4
                        },
                        new
                        {
                            Id = 21,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 26, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2273),
                            StudentId = 5,
                            SubjectId = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 22,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 17, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2274),
                            StudentId = 5,
                            SubjectId = 2,
                            Value = 2
                        },
                        new
                        {
                            Id = 23,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 2, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2275),
                            StudentId = 5,
                            SubjectId = 3,
                            Value = 2
                        },
                        new
                        {
                            Id = 24,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 12, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2276),
                            StudentId = 5,
                            SubjectId = 4,
                            Value = 4
                        },
                        new
                        {
                            Id = 25,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 3, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2277),
                            StudentId = 5,
                            SubjectId = 5,
                            Value = 2
                        },
                        new
                        {
                            Id = 26,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 10, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2278),
                            StudentId = 6,
                            SubjectId = 1,
                            Value = 3
                        },
                        new
                        {
                            Id = 27,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 16, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2282),
                            StudentId = 6,
                            SubjectId = 2,
                            Value = 2
                        },
                        new
                        {
                            Id = 28,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 18, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2284),
                            StudentId = 6,
                            SubjectId = 3,
                            Value = 4
                        },
                        new
                        {
                            Id = 29,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 24, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2285),
                            StudentId = 6,
                            SubjectId = 4,
                            Value = 2
                        },
                        new
                        {
                            Id = 30,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 11, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2286),
                            StudentId = 6,
                            SubjectId = 5,
                            Value = 4
                        },
                        new
                        {
                            Id = 31,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 18, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2295),
                            StudentId = 7,
                            SubjectId = 1,
                            Value = 2
                        },
                        new
                        {
                            Id = 32,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 3, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2296),
                            StudentId = 7,
                            SubjectId = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = 33,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 6, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2297),
                            StudentId = 7,
                            SubjectId = 3,
                            Value = 2
                        },
                        new
                        {
                            Id = 34,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 21, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2300),
                            StudentId = 7,
                            SubjectId = 4,
                            Value = 2
                        },
                        new
                        {
                            Id = 35,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 1, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2300),
                            StudentId = 7,
                            SubjectId = 5,
                            Value = 2
                        },
                        new
                        {
                            Id = 36,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 18, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2302),
                            StudentId = 8,
                            SubjectId = 1,
                            Value = 3
                        },
                        new
                        {
                            Id = 37,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 18, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2303),
                            StudentId = 8,
                            SubjectId = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = 38,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 18, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2304),
                            StudentId = 8,
                            SubjectId = 3,
                            Value = 5
                        },
                        new
                        {
                            Id = 39,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 15, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2305),
                            StudentId = 8,
                            SubjectId = 4,
                            Value = 2
                        },
                        new
                        {
                            Id = 40,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 16, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2305),
                            StudentId = 8,
                            SubjectId = 5,
                            Value = 4
                        },
                        new
                        {
                            Id = 41,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 3, 25, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2307),
                            StudentId = 9,
                            SubjectId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 42,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 26, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2308),
                            StudentId = 9,
                            SubjectId = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = 43,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 16, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2309),
                            StudentId = 9,
                            SubjectId = 3,
                            Value = 4
                        },
                        new
                        {
                            Id = 44,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 10, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2309),
                            StudentId = 9,
                            SubjectId = 4,
                            Value = 3
                        },
                        new
                        {
                            Id = 45,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 2, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2310),
                            StudentId = 9,
                            SubjectId = 5,
                            Value = 3
                        },
                        new
                        {
                            Id = 46,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 25, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2312),
                            StudentId = 10,
                            SubjectId = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 47,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 3, 26, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2312),
                            StudentId = 10,
                            SubjectId = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = 48,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 5, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2313),
                            StudentId = 10,
                            SubjectId = 3,
                            Value = 4
                        },
                        new
                        {
                            Id = 49,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 3, 27, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2315),
                            StudentId = 10,
                            SubjectId = 4,
                            Value = 2
                        },
                        new
                        {
                            Id = 50,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 29, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2315),
                            StudentId = 10,
                            SubjectId = 5,
                            Value = 5
                        },
                        new
                        {
                            Id = 51,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 9, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2317),
                            StudentId = 11,
                            SubjectId = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 52,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 22, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2318),
                            StudentId = 11,
                            SubjectId = 2,
                            Value = 2
                        },
                        new
                        {
                            Id = 53,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 3, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2319),
                            StudentId = 11,
                            SubjectId = 3,
                            Value = 3
                        },
                        new
                        {
                            Id = 54,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 11, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2320),
                            StudentId = 11,
                            SubjectId = 4,
                            Value = 2
                        },
                        new
                        {
                            Id = 55,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 14, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2321),
                            StudentId = 11,
                            SubjectId = 5,
                            Value = 2
                        },
                        new
                        {
                            Id = 56,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 3, 21, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2322),
                            StudentId = 12,
                            SubjectId = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 57,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 9, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2323),
                            StudentId = 12,
                            SubjectId = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = 58,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 1, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2324),
                            StudentId = 12,
                            SubjectId = 3,
                            Value = 4
                        },
                        new
                        {
                            Id = 59,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 3, 21, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2325),
                            StudentId = 12,
                            SubjectId = 4,
                            Value = 4
                        },
                        new
                        {
                            Id = 60,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 17, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2325),
                            StudentId = 12,
                            SubjectId = 5,
                            Value = 4
                        },
                        new
                        {
                            Id = 61,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 3, 25, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2327),
                            StudentId = 13,
                            SubjectId = 1,
                            Value = 3
                        },
                        new
                        {
                            Id = 62,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 6, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2328),
                            StudentId = 13,
                            SubjectId = 2,
                            Value = 2
                        },
                        new
                        {
                            Id = 63,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 16, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2328),
                            StudentId = 13,
                            SubjectId = 3,
                            Value = 3
                        },
                        new
                        {
                            Id = 64,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 14, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2329),
                            StudentId = 13,
                            SubjectId = 4,
                            Value = 2
                        },
                        new
                        {
                            Id = 65,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 13, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2330),
                            StudentId = 13,
                            SubjectId = 5,
                            Value = 3
                        },
                        new
                        {
                            Id = 66,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 11, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2334),
                            StudentId = 14,
                            SubjectId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 67,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 30, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2334),
                            StudentId = 14,
                            SubjectId = 2,
                            Value = 2
                        },
                        new
                        {
                            Id = 68,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 4, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2335),
                            StudentId = 14,
                            SubjectId = 3,
                            Value = 3
                        },
                        new
                        {
                            Id = 69,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 18, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2336),
                            StudentId = 14,
                            SubjectId = 4,
                            Value = 5
                        },
                        new
                        {
                            Id = 70,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 3, 30, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2337),
                            StudentId = 14,
                            SubjectId = 5,
                            Value = 2
                        },
                        new
                        {
                            Id = 71,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 4, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2338),
                            StudentId = 15,
                            SubjectId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 72,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 3, 30, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2339),
                            StudentId = 15,
                            SubjectId = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = 73,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 16, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2340),
                            StudentId = 15,
                            SubjectId = 3,
                            Value = 3
                        },
                        new
                        {
                            Id = 74,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 12, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2341),
                            StudentId = 15,
                            SubjectId = 4,
                            Value = 4
                        },
                        new
                        {
                            Id = 75,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 1, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2342),
                            StudentId = 15,
                            SubjectId = 5,
                            Value = 2
                        },
                        new
                        {
                            Id = 76,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 17, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2343),
                            StudentId = 16,
                            SubjectId = 1,
                            Value = 2
                        },
                        new
                        {
                            Id = 77,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 3, 24, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2344),
                            StudentId = 16,
                            SubjectId = 2,
                            Value = 2
                        },
                        new
                        {
                            Id = 78,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 2, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2345),
                            StudentId = 16,
                            SubjectId = 3,
                            Value = 5
                        },
                        new
                        {
                            Id = 79,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 3, 27, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2346),
                            StudentId = 16,
                            SubjectId = 4,
                            Value = 2
                        },
                        new
                        {
                            Id = 80,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 1, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2347),
                            StudentId = 16,
                            SubjectId = 5,
                            Value = 2
                        },
                        new
                        {
                            Id = 81,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 16, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2348),
                            StudentId = 17,
                            SubjectId = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 82,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 11, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2349),
                            StudentId = 17,
                            SubjectId = 2,
                            Value = 4
                        },
                        new
                        {
                            Id = 83,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 25, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2350),
                            StudentId = 17,
                            SubjectId = 3,
                            Value = 4
                        },
                        new
                        {
                            Id = 84,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 22, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2351),
                            StudentId = 17,
                            SubjectId = 4,
                            Value = 5
                        },
                        new
                        {
                            Id = 85,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 3, 23, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2352),
                            StudentId = 17,
                            SubjectId = 5,
                            Value = 3
                        },
                        new
                        {
                            Id = 86,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 16, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2395),
                            StudentId = 18,
                            SubjectId = 1,
                            Value = 3
                        },
                        new
                        {
                            Id = 87,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 1, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2397),
                            StudentId = 18,
                            SubjectId = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = 88,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 12, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2398),
                            StudentId = 18,
                            SubjectId = 3,
                            Value = 2
                        },
                        new
                        {
                            Id = 89,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 8, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2399),
                            StudentId = 18,
                            SubjectId = 4,
                            Value = 2
                        },
                        new
                        {
                            Id = 90,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 6, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2400),
                            StudentId = 18,
                            SubjectId = 5,
                            Value = 5
                        },
                        new
                        {
                            Id = 91,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 14, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2402),
                            StudentId = 19,
                            SubjectId = 1,
                            Value = 3
                        },
                        new
                        {
                            Id = 92,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 11, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2403),
                            StudentId = 19,
                            SubjectId = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = 93,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 3, 23, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2404),
                            StudentId = 19,
                            SubjectId = 3,
                            Value = 5
                        },
                        new
                        {
                            Id = 94,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 5, 8, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2405),
                            StudentId = 19,
                            SubjectId = 4,
                            Value = 5
                        },
                        new
                        {
                            Id = 95,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 17, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2406),
                            StudentId = 19,
                            SubjectId = 5,
                            Value = 3
                        },
                        new
                        {
                            Id = 96,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 3, 24, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2407),
                            StudentId = 20,
                            SubjectId = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 97,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 4, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2408),
                            StudentId = 20,
                            SubjectId = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = 98,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 28, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2409),
                            StudentId = 20,
                            SubjectId = 3,
                            Value = 3
                        },
                        new
                        {
                            Id = 99,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 4, 1, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2410),
                            StudentId = 20,
                            SubjectId = 4,
                            Value = 4
                        },
                        new
                        {
                            Id = 100,
                            Comment = "Оценка за контрольную работу",
                            Date = new DateTime(2026, 3, 27, 14, 45, 29, 612, DateTimeKind.Utc).AddTicks(2411),
                            StudentId = 20,
                            SubjectId = 5,
                            Value = 2
                        });
                });

            modelBuilder.Entity("StudentPerformanceApi.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Course")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Course = 1,
                            Name = "ИС-101"
                        },
                        new
                        {
                            Id = 2,
                            Course = 1,
                            Name = "ИС-102"
                        },
                        new
                        {
                            Id = 3,
                            Course = 2,
                            Name = "ИС-201"
                        },
                        new
                        {
                            Id = 4,
                            Course = 2,
                            Name = "ИС-202"
                        },
                        new
                        {
                            Id = 5,
                            Course = 3,
                            Name = "ИС-301"
                        });
                });

            modelBuilder.Entity("StudentPerformanceApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "abramov@student.ru",
                            FullName = "Абрамов Сергей Павлович",
                            GroupId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "borisova@student.ru",
                            FullName = "Борисова Анна Владимировна",
                            GroupId = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "vasiliev@student.ru",
                            FullName = "Васильев Павел Андреевич",
                            GroupId = 1
                        },
                        new
                        {
                            Id = 4,
                            Email = "grigorieva@student.ru",
                            FullName = "Григорьева Ольга Николаевна",
                            GroupId = 1
                        },
                        new
                        {
                            Id = 5,
                            Email = "dmitriev@student.ru",
                            FullName = "Дмитриев Андрей Сергеевич",
                            GroupId = 2
                        },
                        new
                        {
                            Id = 6,
                            Email = "egorova@student.ru",
                            FullName = "Егорова Виктория Дмитриевна",
                            GroupId = 2
                        },
                        new
                        {
                            Id = 7,
                            Email = "zhukov@student.ru",
                            FullName = "Жуков Максим Игоревич",
                            GroupId = 2
                        },
                        new
                        {
                            Id = 8,
                            Email = "zaitseva@student.ru",
                            FullName = "Зайцева Екатерина Алексеевна",
                            GroupId = 2
                        },
                        new
                        {
                            Id = 9,
                            Email = "ilin@student.ru",
                            FullName = "Ильин Артём Викторович",
                            GroupId = 3
                        },
                        new
                        {
                            Id = 10,
                            Email = "kozlova@student.ru",
                            FullName = "Козлова Светлана Павловна",
                            GroupId = 3
                        },
                        new
                        {
                            Id = 11,
                            Email = "lebedev@student.ru",
                            FullName = "Лебедев Николай Андреевич",
                            GroupId = 3
                        },
                        new
                        {
                            Id = 12,
                            Email = "morozova@student.ru",
                            FullName = "Морозова Татьяна Сергеевна",
                            GroupId = 3
                        },
                        new
                        {
                            Id = 13,
                            Email = "novikov@student.ru",
                            FullName = "Новиков Денис Валерьевич",
                            GroupId = 4
                        },
                        new
                        {
                            Id = 14,
                            Email = "orlova@student.ru",
                            FullName = "Орлова Юлия Андреевна",
                            GroupId = 4
                        },
                        new
                        {
                            Id = 15,
                            Email = "popov@student.ru",
                            FullName = "Попов Игорь Сергеевич",
                            GroupId = 4
                        },
                        new
                        {
                            Id = 16,
                            Email = "romanova@student.ru",
                            FullName = "Романова Марина Павловна",
                            GroupId = 4
                        },
                        new
                        {
                            Id = 17,
                            Email = "sokolov@student.ru",
                            FullName = "Соколов Владимир Дмитриевич",
                            GroupId = 5
                        },
                        new
                        {
                            Id = 18,
                            Email = "tikhonova@student.ru",
                            FullName = "Тихонова Анастасия Игоревна",
                            GroupId = 5
                        },
                        new
                        {
                            Id = 19,
                            Email = "fedorov@student.ru",
                            FullName = "Федоров Алексей Павлович",
                            GroupId = 5
                        },
                        new
                        {
                            Id = 20,
                            Email = "shestakova@student.ru",
                            FullName = "Шестакова Полина Викторовна",
                            GroupId = 5
                        });
                });

            modelBuilder.Entity("StudentPerformanceApi.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Математика",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Программирование",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Базы данных",
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Веб-разработка",
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Английский язык",
                            TeacherId = 5
                        });
                });

            modelBuilder.Entity("StudentPerformanceApi.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ivanov@college.ru",
                            FullName = "Иванов Иван Иванович"
                        },
                        new
                        {
                            Id = 2,
                            Email = "petrova@college.ru",
                            FullName = "Петрова Мария Сергеевна"
                        },
                        new
                        {
                            Id = 3,
                            Email = "sidorov@college.ru",
                            FullName = "Сидоров Алексей Викторович"
                        },
                        new
                        {
                            Id = 4,
                            Email = "kuznetsova@college.ru",
                            FullName = "Кузнецова Елена Дмитриевна"
                        },
                        new
                        {
                            Id = 5,
                            Email = "smirnov@college.ru",
                            FullName = "Смирнов Дмитрий Александрович"
                        });
                });

            modelBuilder.Entity("StudentPerformanceApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@college.ru",
                            FullName = "Администратор",
                            PasswordHash = "$2a$11$ZRGnGv4.g8oEqG/C/D49VeMmXRe8PBYWlmoSLySVh05Bpgi1gVmMa",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ivanov@college.ru",
                            FullName = "Иванов Иван Иванович",
                            PasswordHash = "$2a$11$RlyDef0dBWX9ZP31VRBGf.FCiV7dHsH3ir3tul7q.UF0Qv0sWOg1W",
                            Role = "Teacher"
                        },
                        new
                        {
                            Id = 3,
                            Email = "abramov@student.ru",
                            FullName = "Абрамов Сергей Павлович",
                            PasswordHash = "$2a$11$zgOoNCXHOdzpo3QJl0ytP.ck8FcQlOb0Qv8tTmuLlW.ujl6ATVha6",
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("StudentPerformanceApi.Models.Grade", b =>
                {
                    b.HasOne("StudentPerformanceApi.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentPerformanceApi.Models.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentPerformanceApi.Models.Student", b =>
                {
                    b.HasOne("StudentPerformanceApi.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("StudentPerformanceApi.Models.Subject", b =>
                {
                    b.HasOne("StudentPerformanceApi.Models.Teacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudentPerformanceApi.Models.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentPerformanceApi.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("StudentPerformanceApi.Models.Subject", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("StudentPerformanceApi.Models.Teacher", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
